# Generated by Django 6.0.6 on 2026-07-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('connection_type', models.CharField(choices=[('postgis', 'PostGIS'), ('geopackage', 'GeoPackage'), ('spatialite', 'SpatiaLite'), ('wms', 'WMS'), ('wfs', 'WFS'), ('xyz', 'XYZ Tiles'), ('raster', 'Raster')], max_length=20)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('database', models.CharField(blank=True, max_length=255)),
                ('schema', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
