# Generated by Django 5.2.13 on 2026-07-08 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_profiles', to='accounts.tenant'),
        ),
        migrations.AlterField(
            model_name='connectionprofile',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
