from django.apps import AppConfig


DEFAULT_THEMES = [
    {
        "name": "MapGuide Classic",
        "description": "Matches the classic MapGuide AJAX Viewer look \u2014 deep navy, gold accents, dock panel layout.",
        "primary_color": "#013466",
        "secondary_color": "#4576a8",
        "background_color": "#ffffff",
        "surface_color": "#eef3f8",
        "text_color": "#1a1a1a",
        "text_muted_color": "#6c757d",
        "border_color": "#b0c4d8",
        "toolbar_bg": "#e8eef4",
        "toolbar_border": "#b0c4d8",
        "panel_bg": "#ffffff",
        "panel_border": "#b0c4d8",
        "statusbar_bg": "#e8eef4",
        "statusbar_border": "#b0c4d8",
        "accent_color": "#eab177",
        "danger_color": "#dc3545",
        "success_color": "#198754",
        "warning_color": "#ffc107",
        "show_toolbar": True,
        "show_legend": True,
        "show_statusbar": True,
        "show_banner": True,
        "banner_title": "MapGuide Classic",
        "banner_subtitle": "AJAX Viewer-style layout",
        "banner_bg": "#013466",
        "banner_text_color": "#ffffff",
        "banner_height": 60,
        "icon_set": "mapguide",
        "layout_preset": "mapguide",
    },
    {
        "name": "MapStore Modern",
        "description": "Matches the MapStore viewer look \u2014 clean white sidebar, Google-blue accent, floating panels.",
        "primary_color": "#1a73e8",
        "secondary_color": "#5f6368",
        "background_color": "#ffffff",
        "surface_color": "#f1f3f4",
        "text_color": "#202124",
        "text_muted_color": "#5f6368",
        "border_color": "#dadce0",
        "toolbar_bg": "#f8f9fa",
        "toolbar_border": "#dadce0",
        "panel_bg": "#ffffff",
        "panel_border": "#dadce0",
        "statusbar_bg": "#f8f9fa",
        "statusbar_border": "#dadce0",
        "accent_color": "#1a73e8",
        "danger_color": "#d93025",
        "success_color": "#1e8e3e",
        "warning_color": "#f9ab00",
        "show_toolbar": True,
        "show_legend": True,
        "show_statusbar": True,
        "show_banner": True,
        "banner_title": "MapStore Modern",
        "banner_subtitle": "Sidebar + floating panels layout",
        "banner_bg": "#2c3e50",
        "banner_text_color": "#ffffff",
        "banner_height": 60,
        "icon_set": "mapstore",
        "layout_preset": "mapstore",
    },
    {
        "name": "QWC2 Default",
        "description": "Matches the QWC2 viewer look \u2014 dark top navbar, slide-out panel, clean white map area.",
        "primary_color": "#1a73e8",
        "secondary_color": "#5f6368",
        "background_color": "#ffffff",
        "surface_color": "#f1f3f4",
        "text_color": "#202124",
        "text_muted_color": "#5f6368",
        "border_color": "#dadce0",
        "toolbar_bg": "#f8f9fa",
        "toolbar_border": "#dadce0",
        "panel_bg": "#ffffff",
        "panel_border": "#dadce0",
        "statusbar_bg": "#f8f9fa",
        "statusbar_border": "#dadce0",
        "accent_color": "#1a73e8",
        "danger_color": "#d93025",
        "success_color": "#1e8e3e",
        "warning_color": "#f9ab00",
        "show_toolbar": True,
        "show_legend": True,
        "show_statusbar": True,
        "show_banner": False,
        "banner_title": "QWC2 Default",
        "banner_subtitle": "Navbar + slide-out panel layout",
        "banner_bg": "#3c4a5a",
        "banner_text_color": "#ffffff",
        "banner_height": 42,
        "icon_set": "default",
        "layout_preset": "qwc2",
    },
    {
        "name": "GeoRidge Dark",
        "description": "Dark theme with blue accent for low-light environments.",
        "primary_color": "#0d6efd",
        "secondary_color": "#adb5bd",
        "background_color": "#1a1a2e",
        "surface_color": "#16213e",
        "text_color": "#eaeaea",
        "text_muted_color": "#9ca3af",
        "border_color": "#374151",
        "toolbar_bg": "#16213e",
        "toolbar_border": "#374151",
        "panel_bg": "#1a1a2e",
        "panel_border": "#374151",
        "statusbar_bg": "#16213e",
        "statusbar_border": "#374151",
        "accent_color": "#0d6efd",
        "danger_color": "#ef4444",
        "success_color": "#22c55e",
        "warning_color": "#f59e0b",
        "show_toolbar": True,
        "show_legend": True,
        "show_statusbar": True,
        "show_banner": True,
        "banner_bg": "#1a1a2e",
        "layout_preset": "mapguide",
    },
    {
        "name": "High Contrast",
        "description": "Maximum contrast black/white/yellow theme for accessibility.",
        "primary_color": "#ffff00",
        "secondary_color": "#ffffff",
        "background_color": "#000000",
        "surface_color": "#1a1a1a",
        "text_color": "#ffffff",
        "text_muted_color": "#cccccc",
        "border_color": "#ffffff",
        "toolbar_bg": "#000000",
        "toolbar_border": "#ffffff",
        "panel_bg": "#000000",
        "panel_border": "#ffffff",
        "statusbar_bg": "#000000",
        "statusbar_border": "#ffffff",
        "accent_color": "#ffff00",
        "danger_color": "#ff4444",
        "success_color": "#44ff44",
        "warning_color": "#ffff00",
        "show_toolbar": True,
        "show_legend": True,
        "show_statusbar": True,
        "banner_bg": "#000000",
        "banner_text_color": "#ffff00",
        "layout_preset": "mapguide",
    },
    {
        "name": "Forest",
        "description": "Green-tinted nature-inspired branded theme.",
        "primary_color": "#2d6a4f",
        "secondary_color": "#52b788",
        "background_color": "#f0f7f4",
        "surface_color": "#d8f3dc",
        "text_color": "#1b4332",
        "text_muted_color": "#52b788",
        "border_color": "#95d5b2",
        "toolbar_bg": "#d8f3dc",
        "toolbar_border": "#95d5b2",
        "panel_bg": "#ffffff",
        "panel_border": "#95d5b2",
        "statusbar_bg": "#d8f3dc",
        "statusbar_border": "#95d5b2",
        "accent_color": "#2d6a4f",
        "danger_color": "#dc3545",
        "success_color": "#40916c",
        "warning_color": "#ffc107",
        "show_toolbar": True,
        "show_legend": True,
        "show_statusbar": True,
        "banner_bg": "#1b4332",
        "layout_preset": "mapguide",
    },
    {
        "name": "Minimal",
        "description": "Bare map with search bar and base map switcher only.",
        "primary_color": "#0d6efd",
        "secondary_color": "#6c757d",
        "background_color": "#ffffff",
        "surface_color": "#f8f9fa",
        "text_color": "#212529",
        "text_muted_color": "#6c757d",
        "border_color": "#dee2e6",
        "toolbar_bg": "#f8f9fa",
        "toolbar_border": "#dee2e6",
        "panel_bg": "#ffffff",
        "panel_border": "#dee2e6",
        "statusbar_bg": "#f8f9fa",
        "statusbar_border": "#dee2e6",
        "accent_color": "#0d6efd",
        "danger_color": "#dc3545",
        "success_color": "#198754",
        "warning_color": "#ffc107",
        "show_toolbar": False,
        "show_legend": False,
        "show_statusbar": False,
        "show_banner": False,
        "layout_preset": "map-only",
    },
    {
        "name": "Warm Sunset",
        "description": "Orange and amber branded warm theme.",
        "primary_color": "#ff6b35",
        "secondary_color": "#f7c59f",
        "background_color": "#fff8f0",
        "surface_color": "#fef0e6",
        "text_color": "#4a2c1a",
        "text_muted_color": "#b07d5e",
        "border_color": "#f7c59f",
        "toolbar_bg": "#fef0e6",
        "toolbar_border": "#f7c59f",
        "panel_bg": "#ffffff",
        "panel_border": "#f7c59f",
        "statusbar_bg": "#fef0e6",
        "statusbar_border": "#f7c59f",
        "accent_color": "#ff6b35",
        "danger_color": "#dc3545",
        "success_color": "#198754",
        "warning_color": "#ffc107",
        "show_toolbar": True,
        "show_legend": True,
        "show_statusbar": True,
        "banner_bg": "#a8481a",
        "layout_preset": "mapguide",
    },
    {
        "name": "Ocean",
        "description": "Blue and teal aquatic-themed colours.",
        "primary_color": "#0077b6",
        "secondary_color": "#90e0ef",
        "background_color": "#f0faff",
        "surface_color": "#caf0f8",
        "text_color": "#03045e",
        "text_muted_color": "#0077b6",
        "border_color": "#90e0ef",
        "toolbar_bg": "#caf0f8",
        "toolbar_border": "#90e0ef",
        "panel_bg": "#ffffff",
        "panel_border": "#90e0ef",
        "statusbar_bg": "#caf0f8",
        "statusbar_border": "#90e0ef",
        "accent_color": "#0077b6",
        "danger_color": "#dc3545",
        "success_color": "#00b4d8",
        "warning_color": "#ffc107",
        "show_toolbar": True,
        "show_legend": True,
        "show_statusbar": True,
        "banner_bg": "#0077b6",
        "layout_preset": "mapguide",
    },
]

DEFAULT_BASE_MAPS = [
    {
        "name": "OpenStreetMap",
        "type": "xyz",
        "url": "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
        "attribution": "\u00a9 OpenStreetMap contributors",
        "sort_order": 0,
    },
    {
        "name": "Satellite (Esri)",
        "type": "xyz",
        "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        "attribution": "\u00a9 Esri",
        "sort_order": 1,
    },
    {
        "name": "Terrain (Esri)",
        "type": "xyz",
        "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer/tile/{z}/{y}/{x}",
        "attribution": "\u00a9 Esri",
        "sort_order": 2,
    },
]


def seed_viewer_defaults(apps, **kwargs):
    ThemeProfile = apps.get_model("viewer", "ThemeProfile")
    BaseMap = apps.get_model("viewer", "BaseMap")

    for data in DEFAULT_THEMES:
        ThemeProfile.objects.get_or_create(name=data["name"], defaults=data)

    for data in DEFAULT_BASE_MAPS:
        BaseMap.objects.get_or_create(name=data["name"], defaults=data)


class ViewerConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "georidge_platform.apps.viewer"
    label = "viewer"

    def ready(self):
        from django.db.models.signals import post_migrate
        post_migrate.connect(seed_viewer_defaults, sender=self)
