services:
  app:
    build: .
    container_name: georidge
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-change-me}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,georidge}
      - DJANGO_SETTINGS_MODULE=georidge_platform.settings.dev
      - DJANGO_DB_NAME=/app/data/db.sqlite3
      - QGIS_SERVER_URL=http://qgis-server:80/qgis
      - QGIS_SERVER_PROJECTS_PATH=/var/www/qgis-server/projects
      - QGIS_SERVER_PREVIEW_PATH=/app/qgis_preview
      - QGIS_SERVER_MAP_PATH_PREFIX=/var/www/qgis-server/media
    volumes:
      - app-media:/app/media
      - app-db:/app/data
      - qgis-data:/var/www/qgis-server/projects
    depends_on:
      - qgis-server
    networks:
      - georidge-network

  qgis-server:
    image: qgis/qgis-server:3.44.12-noble
    container_name: qgis-server
    platform: linux/amd64
    environment:
      - QGIS_SERVER_LOG_LEVEL=0
      - QGIS_SERVER_LANDING_PAGE_PREFIX=/qgis
    volumes:
      - qgis-data:/var/www/qgis-server/projects
      - app-media:/var/www/qgis-server/media
    networks:
      - georidge-network

volumes:
  app-media:
  app-db:
  qgis-data:

networks:
  georidge-network:
    driver: bridge
