# Generated by Django 5.2.13 on 2026-07-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_migrate_published_data_to_project'),
        ('viewer', '0002_themeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='viewer.themeprofile'),
        ),
    ]
