# Generated by Django 5.2.13 on 2026-07-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
        ('projects', '0005_project_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.tenant'),
        ),
    ]
