# Generated by Django 5.2.13 on 2026-07-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_tenant'),
        ('viewer', '0007_basemap_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='base_maps',
            field=models.ManyToManyField(blank=True, help_text='Base maps available for this project. Leave empty to use all active base maps for the tenant.', to='viewer.basemap'),
        ),
    ]
