# Generated by Django 6.0.7 on 2026-07-14 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('viewer', '0002_themeprofile'), ('viewer', '0003_seed_default_theme'), ('viewer', '0004_themeprofile_tenant'), ('viewer', '0005_themeprofile_banner_icons'), ('viewer', '0006_themeprofile_banner_image'), ('viewer', '0007_basemap_model'), ('viewer', '0008_layersearchconfig'), ('viewer', '0009_layersearchconfig_available_fields_and_more'), ('viewer', '0010_alter_themeprofile_layout_preset'), ('viewer', '0011_remove_weblayout'), ('viewer', '0012_layer_search_config_tweaks'), ('viewer', '0013_seed_platform_defaults'), ('viewer', '0014_update_ocean_banner'), ('viewer', '0015_add_popup_fields_to_layersearchconfig'), ('viewer', '0016_fix_minimal_and_maponly_themes'), ('viewer', '0017_remove_maponly_fix_dark_banner')]

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('xyz', 'XYZ')], default='xyz', max_length=20)),
                ('url', models.CharField(help_text='Tile URL template, e.g. https://tile.openstreetmap.org/{z}/{x}/{y}.png', max_length=1024)),
                ('attribution', models.CharField(blank=True, default='', max_length=1024)),
                ('thumbnail', models.ImageField(blank=True, upload_to='basemaps/thumbnails/')),
                ('min_zoom', models.IntegerField(default=0)),
                ('max_zoom', models.IntegerField(default=19)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Leave blank for global (available to all tenants).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_maps', to='accounts.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ThemeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, upload_to='themes/logos/')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('surface_color', models.CharField(default='#f8f9fa', max_length=7)),
                ('text_color', models.CharField(default='#212529', max_length=7)),
                ('text_muted_color', models.CharField(default='#6c757d', max_length=7)),
                ('border_color', models.CharField(default='#dee2e6', max_length=7)),
                ('toolbar_bg', models.CharField(default='#f8f9fa', max_length=7)),
                ('toolbar_border', models.CharField(default='#dee2e6', max_length=7)),
                ('panel_bg', models.CharField(default='#ffffff', max_length=7)),
                ('panel_border', models.CharField(default='#dee2e6', max_length=7)),
                ('statusbar_bg', models.CharField(default='#f8f9fa', max_length=7)),
                ('statusbar_border', models.CharField(default='#dee2e6', max_length=7)),
                ('accent_color', models.CharField(default='#0d6efd', max_length=7)),
                ('danger_color', models.CharField(default='#dc3545', max_length=7)),
                ('success_color', models.CharField(default='#198754', max_length=7)),
                ('warning_color', models.CharField(default='#ffc107', max_length=7)),
                ('show_legend', models.BooleanField(default=True)),
                ('show_toolbar', models.BooleanField(default=True)),
                ('show_statusbar', models.BooleanField(default=True)),
                ('layout_preset', models.CharField(choices=[('mapguide', 'MapGuide'), ('mapstore', 'MapStore'), ('qwc2', 'QWC2'), ('map-only', 'Map Only')], default='mapguide', help_text='MapGuide: classic dock panel. MapStore: sidebar + floating panels. QWC2: navbar + slide-out panel. Map Only: bare map.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, help_text='Group whose projects can use this theme. Leave blank for global.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this theme belongs to. Leave blank for global themes available to all tenants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='accounts.tenant')),
                ('banner_bg', models.CharField(default='#004282', max_length=7)),
                ('banner_height', models.PositiveIntegerField(default=60, help_text='Banner height in pixels.')),
                ('banner_subtitle', models.CharField(blank=True, default='', help_text='Smaller text displayed below the title.', max_length=255)),
                ('banner_text_color', models.CharField(default='#ffffff', max_length=7)),
                ('banner_title', models.CharField(blank=True, default='', help_text='Main banner text. Falls back to project name if blank.', max_length=255)),
                ('icon_set', models.CharField(default='default', help_text='Name of the icon set directory under viewer/static/viewer/icons/.', max_length=64)),
                ('show_banner', models.BooleanField(default=True)),
                ('banner_image', models.ImageField(blank=True, help_text='Background image positioned at the right edge of the banner (e.g., corner graphic).', upload_to='themes/banners/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LayerSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, default=None, help_text='WMS layer name from QGIS', max_length=255, null=True)),
                ('layer_title', models.CharField(blank=True, default='', help_text='Display name from QGIS', max_length=255)),
                ('searchable_fields', models.JSONField(blank=True, default=list, help_text='Currently selected field names')),
                ('label_template', models.CharField(blank=True, default='{id}', help_text="Template for result labels, e.g. '{owner} - {address}'", max_length=512)),
                ('max_results', models.IntegerField(default=5, help_text='Maximum results per layer')),
                ('active', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_configs', to='projects.project')),
                ('available_fields', models.JSONField(blank=True, default=list, help_text='Complete field list from last sync')),
                ('popup_fields', models.CharField(blank=True, default='', help_text="Comma-separated field names to show in the search result popup, e.g. 'section, lot, block'", max_length=512)),
            ],
            options={
                'ordering': ['order', 'layer_name'],
                'unique_together': {('project', 'layer_name')},
                'verbose_name': 'Layer search config',
                'verbose_name_plural': 'Layer search configs',
            },
        ),
    ]
