# Generated by Django 6.0.6 on 2026-07-01 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('show_legend', models.BooleanField(default=True)),
                ('show_toolbar', models.BooleanField(default=True)),
                ('show_statusbar', models.BooleanField(default=True)),
                ('initial_extent', models.JSONField(blank=True, null=True)),
                ('default_layers', models.JSONField(blank=True, default=list)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='projects.project')),
            ],
        ),
    ]
