# Generated by Django 5.2.13 on 2026-07-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, upload_to='themes/logos/')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('surface_color', models.CharField(default='#f8f9fa', max_length=7)),
                ('text_color', models.CharField(default='#212529', max_length=7)),
                ('text_muted_color', models.CharField(default='#6c757d', max_length=7)),
                ('border_color', models.CharField(default='#dee2e6', max_length=7)),
                ('toolbar_bg', models.CharField(default='#f8f9fa', max_length=7)),
                ('toolbar_border', models.CharField(default='#dee2e6', max_length=7)),
                ('panel_bg', models.CharField(default='#ffffff', max_length=7)),
                ('panel_border', models.CharField(default='#dee2e6', max_length=7)),
                ('statusbar_bg', models.CharField(default='#f8f9fa', max_length=7)),
                ('statusbar_border', models.CharField(default='#dee2e6', max_length=7)),
                ('accent_color', models.CharField(default='#0d6efd', max_length=7)),
                ('danger_color', models.CharField(default='#dc3545', max_length=7)),
                ('success_color', models.CharField(default='#198754', max_length=7)),
                ('warning_color', models.CharField(default='#ffc107', max_length=7)),
                ('show_legend', models.BooleanField(default=True)),
                ('show_toolbar', models.BooleanField(default=True)),
                ('show_statusbar', models.BooleanField(default=True)),
                ('layout_preset', models.CharField(choices=[('full', 'Full'), ('map-only', 'Map Only')], default='full', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, help_text='Group whose projects can use this theme. Leave blank for global.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
