# Generated by Django 6.0.7 on 2026-07-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeprofile',
            name='layout_preset',
            field=models.CharField(choices=[('mapguide', 'MapGuide'), ('mapstore', 'MapStore'), ('qwc2', 'QWC2'), ('map-only', 'Map Only'), ('lizmap', 'Lizmap')], default='mapguide', help_text='MapGuide: classic dock panel. MapStore: sidebar + floating panels. QWC2: navbar + slide-out panel. Lizmap: sidebar + tabbed dock. Map Only: bare map.', max_length=20),
        ),
    ]
