# Generated by Django 5.2.13 on 2026-07-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
        ('viewer', '0003_seed_default_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this theme belongs to. Leave blank for global themes available to all tenants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='accounts.tenant'),
        ),
    ]
