# Generated by Django 5.2.13 on 2026-07-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_themeprofile_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeprofile',
            name='banner_bg',
            field=models.CharField(default='#004282', max_length=7),
        ),
        migrations.AddField(
            model_name='themeprofile',
            name='banner_height',
            field=models.PositiveIntegerField(default=60, help_text='Banner height in pixels.'),
        ),
        migrations.AddField(
            model_name='themeprofile',
            name='banner_subtitle',
            field=models.CharField(blank=True, default='', help_text='Smaller text displayed below the title.', max_length=255),
        ),
        migrations.AddField(
            model_name='themeprofile',
            name='banner_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='themeprofile',
            name='banner_title',
            field=models.CharField(blank=True, default='', help_text='Main banner text. Falls back to project name if blank.', max_length=255),
        ),
        migrations.AddField(
            model_name='themeprofile',
            name='icon_set',
            field=models.CharField(default='default', help_text='Name of the icon set directory under viewer/static/viewer/icons/.', max_length=64),
        ),
        migrations.AddField(
            model_name='themeprofile',
            name='show_banner',
            field=models.BooleanField(default=True),
        ),
    ]
