# Generated by Django 5.2.13 on 2026-07-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_themeprofile_banner_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeprofile',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Background image positioned at the right edge of the banner (e.g., corner graphic).', upload_to='themes/banners/'),
        ),
    ]
