# Generated by Django 5.2.13 on 2026-07-08 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_user_tenant'),
        ('viewer', '0006_themeprofile_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('xyz', 'XYZ')], default='xyz', max_length=20)),
                ('url', models.CharField(help_text='Tile URL template, e.g. https://tile.openstreetmap.org/{z}/{x}/{y}.png', max_length=1024)),
                ('attribution', models.CharField(blank=True, default='', max_length=1024)),
                ('thumbnail', models.ImageField(blank=True, upload_to='basemaps/thumbnails/')),
                ('min_zoom', models.IntegerField(default=0)),
                ('max_zoom', models.IntegerField(default=19)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Leave blank for global (available to all tenants).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_maps', to='accounts.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
