# Generated by Django 5.2.13 on 2026-07-08 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_base_maps'),
        ('viewer', '0007_basemap_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(help_text='WMS layer name from QGIS', max_length=255)),
                ('layer_title', models.CharField(blank=True, default='', help_text='Display name from QGIS', max_length=255)),
                ('searchable_fields', models.JSONField(blank=True, default=list, help_text='List of field names to search')),
                ('label_template', models.CharField(blank=True, default='{id}', help_text="Template for result labels, e.g. '{owner} - {address}'", max_length=512)),
                ('max_results', models.IntegerField(default=5, help_text='Maximum results per layer')),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_configs', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'layer_name'],
                'unique_together': {('project', 'layer_name')},
            },
        ),
    ]
