# Generated by Django 5.2.13 on 2026-07-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_layersearchconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersearchconfig',
            name='available_fields',
            field=models.JSONField(blank=True, default=list, help_text='Complete field list from last sync'),
        ),
        migrations.AlterField(
            model_name='layersearchconfig',
            name='searchable_fields',
            field=models.JSONField(blank=True, default=list, help_text='Currently selected field names'),
        ),
    ]
