# Generated by Django 5.2.13 on 2026-07-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_alter_themeprofile_layout_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeprofile',
            name='layout_preset',
            field=models.CharField(choices=[('mapguide', 'MapGuide'), ('mapstore', 'MapStore'), ('qwc2', 'QWC2'), ('map-only', 'Map Only')], default='mapguide', help_text='MapGuide: classic dock panel. MapStore: sidebar + floating panels. QWC2: navbar + slide-out panel. Map Only: bare map.', max_length=20),
        ),
        migrations.DeleteModel(
            name='WebLayout',
        ),
    ]
