# Generated by Django 5.2.13 on 2026-07-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_remove_weblayout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layersearchconfig',
            options={'ordering': ['order', 'layer_name'], 'verbose_name': 'Layer search config', 'verbose_name_plural': 'Layer search configs'},
        ),
        migrations.AlterField(
            model_name='layersearchconfig',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='layersearchconfig',
            name='layer_name',
            field=models.CharField(blank=True, default=None, help_text='WMS layer name from QGIS', max_length=255, null=True),
        ),
    ]
