# Generated by Django 5.2.13 on 2026-07-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_update_ocean_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersearchconfig',
            name='popup_fields',
            field=models.CharField(blank=True, default='', help_text="Comma-separated field names to show in the search result popup, e.g. 'section, lot, block'", max_length=512),
        ),
    ]
