# Generated by Django 5.2.13 on 2026-07-02 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publishedproject",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publishing_record",
                to="projects.project",
            ),
        ),
    ]
